runtime: php73

handlers:
  - url: /(.+\.(gif|png|jpg|pdf|ico))$
    static_files: \1
    upload: .+\.(gif|png|jpg|pdf|ico)$
    secure: always

  - url: .*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 3
  max_idle_instances: 1