#service: website
runtime: php73

handlers:
  # Serve images as static resources.
  - url: /(.+\.(gif|png|jpg))$
    static_files: \1
    upload: .+\.(gif|png|jpg)$
    secure: always
  
  # Serve your app through a front controller at index.php or public/index.php.
  - url: .*
    script: auto
    secure: always